---
title: "作ったものの置き場"
author: ""
date: ""
output: 
  html_document
---

---

[GitHub](https://github.com/suzuna)

- 記事内で非表示になっているコードは、"Code"を押すと表示できます。
  - 記事のタイトルの右上の"Code" > "Show All Code"を押すと記事内の全てのコードを表示できます。
- 記事中に記載がない限り、記事内のコードはRです。

## 作ったもの

### データ分析

- [東京電力株のベータ値をカルマンフィルタで推定する](./posts/20220130_beta_tepco.html)
  - 東京電力HD株のベータ値をカルマンフィルタで推定しました。
  
- [TOPIXのボラティリティをStanで推定する](./posts/20220201_svmodel.html)
  - 非線形な状態空間モデルであるStochastic Volatilityモデルによって、TOPIXのボラティリティをStanで推定しました。

- [ITmedia NEWSの全記事を用いてIT分野の流行語を調べた](./posts/20210912_ITmedia_news_analysis.html)
  - ITmedia NEWSの記事データについて、TF-IDFを用いて毎年の「その年のIT分野の世相を表す単語」をピックアップしました。

### Webアプリ

- [ニコニコ検索](https://github.com/suzuna/niconico-search)
  - ニコニコ動画を検索するWebアプリです。
  - 公式では行えない、再生数などに上限、下限を設定したり、マイリスト率やマイリスト率/コメント率などの大小でソートして結果を表示する検索ができます。
  - Shinyで実装しています。裏側ではニコニコ動画のAPIを叩いています。
- [ITnewsheader](https://github.com/suzuna/itnewsheader)
  - ITニュースサイトより、最新のITニュースタイトルの一覧を表示します。取得したニュースタイトルから検索することもできます。
  - Shinyで実装しています。
  
### ライブラリ
- [mecabtools](https://github.com/suzuna/mecabtools)
  - RMeCabの出力をtidy textなdata.frameとして返すRのパッケージです。

## 小ネタ

- 2020/04/30 [タイムゾーンを指定した時のlubridate::parse_date_timeとlubridate::parse_date_time2の速度の違い](./posts/20200430_parse_date_time.html)
- 2021/02/08 [RMeCabで形態素解析した結果をtidy textなdata.frameで取得する](./posts/20210208_rmecab_tidy_text_result.html)
- 2021/02/18 [RMarkdownにhighlight.jsのcssテーマを適用する](./posts/20210218_rmarkdown_highlightjs_css.html)
