---
title: "RMarkdownにhighlight.jsのcssテーマを適用する"
author: ""
date: "2021-02-18"
output: 
  html_document:
    self_contained: false
    lib_dir: libs
    number_sections: false
    toc: false
    toc_depth: 1
    keep_md: false
    css: main.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,include=TRUE,tidy=FALSE,message=FALSE,warning=FALSE,error=FALSE,cache=FALSE)
knitr::opts_chunk$set(out.width="100%",out.height="50%",fig.height=2,fig.align="center")
library(tidyverse)
library(magrittr)
library(knitr)
```

## RMarkdownにhighlight.jsのcssテーマを適用する

highlight.jsのcssテーマを用いてRMarkdownのコードハイライトを変更する方法を示します。

RMarkdownはYAML部分のオプションを用いてコード部分のハイライトを変更することができます。例えば以下の記事をご覧ください。

[R Markdownでコードハイライトのテーマ設定](https://qiita.com/kazutan/items/ca20f26fba3f6fba81c5)

しかし、設定できるコードハイライトのテーマがdefault,tango,pygments,kate,monochrome,espresso,zenburn,haddock,textmateの9パターンしかありません。

一方、highlight.jsにはたくさんの綺麗なテーマがあります。2021年2月のバージョン10.5.0時点で97パターンあります。

そこで、[highlightjs と highlightjs-line-numbers プラグインで Rmarkdown のコードブロックに行番号をつける](https://blog.atusy.net/2019/04/22/rmd-line-num-with-highlightjs/)を参考にしながら、highlight.jsのcssテーマをRMarkdownのコードハイライトに当てる方法を考えました。

結論としては、以下のコードをRMarkdownのYAML部分の直下（＝本文部分の先頭）に記載します。

````
<style type="text/css">
@import "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/styles/rainbow.min.css";
</style>

```{`r "css"`, echo=FALSE}
pre{
  border: transparent;
  background: transparent;
  padding: 0px;
}

/* preのpadding 9.5px + border 1px */
code.hljs{
  padding: 10.5px;
}
```
````

@importで読み込むhighlight.jsのCDNのアドレスの最後の"rainbow.min.css"の"rainbow"は、[highlight.jsのGitHubのリポジトリ](https://github.com/highlightjs/highlight.js/tree/master/src/styles)にある"テーマ名.css"の"テーマ名"です。[highlight.jsのdemo](https://highlightjs.org/static/demo/)で使いたいテーマを見つけたら、このリポジトリからテーマ名を探します。CDNで読み込むときはテーマ名に.minを付けます。

RMarkdownのコードブロックでは、border: 1px, padding: 9.5pxのpreという要素の中に、code.hljsという要素のコード部分が存在します。上のコードの最初の3行（style～/style部分）だけをRMarkdownに書いてcssを変更しないと、code.hljsはテーマの背景に変わっているのに、borderとpaddingはデフォルトのグレーのまま残ってしまいます。highlight.jsのcssはcode.hljsにかかるので、上のようにpreのborderとbackgroundをcode.hljsの透過としてpaddingをいじることで、見た目をうまく調節しています。

## おまけ（フォント変更）

以下を追加することで、RMarkdownのコード部分のフォントをコード用のフォントに変えられます。

````
```{`r "css"`, echo=FALSE}
code{
  font-family: SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace;
}
```
````

インラインのコードのフォントも変わります。

## 環境

Rは4.0.2、RMarkdownは2.7、highlight.jsは10.5.0のバージョンを使用しています。
